### PR TITLE
Remove negation since I think it was a typo

### PR DESCRIPTION
**Pull request by thisisambros**
To my understanding full-nodes will recognise that this is an invalid chain, hence the negation there is just a typo

### CODE REVIEW

**Review by fresheneesz — APPROVED** [review]

**Comment by fresheneesz** [comment]
Thanks for the fix!

**Review by fresheneesz — COMMENTED** [review]
Actually, what I meant by "won't recognize it" is that they won't recognize the forked chain as valid. Maybe its not clear what "it" was. Maybe would you mind rephrasing to "Full nodes will recognize that the forked chain is invalid, however light nodes would currently follow the longest chain even if its not valid, in most cases."

Thanks for pointing out the ambiguity!

**Comment by thisisambros** [comment]
Thanks for your patience. I have updated the sentence as per your proposal.
Thanks for the great work! This really is an amazing article

**Comment by fresheneesz** [comment]
Thanks again!

**Pull request merged**
